version: '2'
volumes:
  data:
  broker_data:
networks:
  xapo_network:
services:
  db:
    image: 'mysql:5.6'
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
      - MYSQL_DATABASE=xapo_currency_api
    hostname: db
    networks:
      xapo_network:
        aliases:
          - &db_host db
  currency_api:
    image: 'currency_api:latest'
    environment:
      - DB_HOST=db
      - DB_PASSWORD=passwd
      - DB_USER=root
      - DB_DATABASE=xapo_currency_api
      - BROKER_URL=redis://broker:6379
    ports:
      - "9000:9000"
    hostname: app
    networks:
      xapo_network:
        aliases:
          - &app_host app

      

    

